channels:
- conda-forge
dependencies:
- python
- atomistics =0.3.7
- cloudpickle =3.1.2
- pyzmq =27.1.0
- flux-core =0.85.0
- flux-pmix =0.6.0
- iprpy-data =2025.01.14
- lammps =2025.07.22=*openmpi*
- lammpsparser =0.0.5
- pylammpsmpi =0.4.1
- pysqa =0.4.2
- h5py =3.16.0
- pip
- pip:
  - git+https://github.com/pyiron/executorlib.git@fix/init-function-mpi-parallel-block-allocation
