channels:
- conda-forge
dependencies:
- python
- atomistics =0.3.7
- executorlib =1.9.3
- flux-core =0.84.0
- flux-pmix =0.6.0
- iprpy-data =2025.01.14
- lammps =2025.07.22=*openmpi*
- lammpsparser =0.0.5
- pylammpsmpi =0.4.1
- pysqa =0.4.2
- h5py =3.16.0
