channels:
- conda-forge
dependencies:
- python
- atomistics =0.3.6
- executorlib =1.9.2
- flux-core =0.85.0
- iprpy-data =2023.07.25
- lammps =2024.08.29=*openmpi*
- lammpsparser =0.0.3
- pylammpsmpi =0.3.12
